# Generated by Django 3.2.12 on 2024-12-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nome do paciente', max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
